name: Test build and pack

on:
  push:
    branches:
      - main

jobs:
  build-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install deps
        run: |
          dotnet restore webapp-base-dotnet.sln
      - name: Build
        run: |
          dotnet build webapp-base-dotnet.sln --configuration Release --no-restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}
      - name: Pack
        run: |
          dotnet pack webapp-base-dotnet.sln --configuration Release --no-restore --no-build -p:BuildNumber=${{ github.run_number }} -p:Deterministic=true
