name: Pack and publish nuget

on:
  release:
    types:
      - published

jobs:
  build-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install deps
        run: |
          dotnet restore dotnet-reflection.sln
      - name: Build
        run: |
          dotnet build dotnet-reflection.sln --configuration Release --no-restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}
      - name: Pack
        run: |
          dotnet pack dotnet-reflection.sln --configuration Release --no-restore --no-build -p:BuildNumber=${{ github.run_number }} -p:Deterministic=true
      - name: Publish Interfaces
        if: startsWith(github.ref, 'refs/tags/interfaces-')
        run: |
          dotnet nuget push lib/Tjololo.DI.Interfaces/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      - name: Publish Defaults
        if: startsWith(github.ref, 'refs/tags/defaults-')
        run: |
          dotnet nuget push lib/Tjololo.DI.Defaults/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}